# my global config
global:
  scrape_interval:     15s
  evaluation_interval: 30s

scrape_configs:
  - job_name: 'prometheus_scraper'
    scrape_interval:  5s
    metrics_path: '/actuator/prometheus'
    scheme: 'http'
    static_configs:
    - targets: ['192.168.0.104:8080']
