scrape_configs:
  - job_name:       'prometheus-scraper'

    # Override the global default and scrape targets from this job every 5 seconds.
    scrape_interval: 5s

    static_configs:
      - targets: ['localhost:9090']
        labels:
          group: 'dev'
